name: Build Project

on: 
  push:
    branches: [ "main", "workflow" ]
  workflow_dispatch:

jobs:
  build:
    name: Build App
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Cache Unity Library
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library
          restore-keys: |
            Library

      # Build
      - name: Build App
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildName: ChuniXR
          buildsPath: exported
          customParameters: '-debugSymbols false'

      # Remove debug symbols (ChuniXR_BackUpThisFolder_ButDontShipItWithYourGame)
      - name: Remove Debug Symbols
        run: |
          $debug_symbols_path = "exported/StandaloneWindows64/ChuniXR_BackUpThisFolder_ButDontShipItWithYourGame"
          if (Test-Path $debug_symbols_path) {
            Remove-Item -Recurse -Force $debug_symbols_path
            Write-Host "Debug symbols folder removed."
          } else {
            Write-Host "Debug symbols folder not found."
          }
        shell: powershell
      
      # Upload exported build
      - uses: actions/upload-artifact@v4
        with:
          name: Exported
          path: exported
          compression-level: 3
