name: Build Project

on: 
  push:
    branches:
      - [ main, workflow ]
  workflow_dispatch:

jobs:
  build:
    name: Build App
    runs-on: windows-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Create Unity Cache Directory
        run: |
          mkdir -p C:/Users/ContainerAdministrator/AppData/Local/Unity/Caches

      # Build
      - name: Build App
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildsPath: exported

      # Upload exported Android Studio project
      - uses: actions/upload-artifact@v4
        with:
          name: Exported
          path: exported
