name: check env

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Commit files
      env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      run: |
        echo ${{secrets.UNITY_LICENSE}} | sed 's/./& /g'
        echo ${{secrets.UNITY_EMAIL}} | sed 's/./& /g'
        echo ${{secrets.UNITY_PASSWORD}} | sed 's/./& /g'
